apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ch4kfalew-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/ch4kfalew-dotnet-basic